
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#ifndef GVC_ENUM_TYPES_H
#define GVC_ENUM_TYPES_H

#include <glib-object.h>

G_BEGIN_DECLS
GType gvc_mixer_stream_state_get_type (void) G_GNUC_CONST;
#define GVC_TYPE_MIXER_STREAM_STATE (gvc_mixer_stream_state_get_type())
G_END_DECLS

#endif

/* Generated data ends here */

