/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "gf-sd-rfkill-gen.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  guint use_gvariant : 1;
  guint emits_changed_signal : 1;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface org.gnome.SettingsDaemon.Rfkill
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:GfSdRfkillGen
 * @title: GfSdRfkillGen
 * @short_description: Generated C code for the org.gnome.SettingsDaemon.Rfkill D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-org-gnome-SettingsDaemon-Rfkill.top_of_page">org.gnome.SettingsDaemon.Rfkill</link> D-Bus interface in C.
 */

/* ---- Introspection data for org.gnome.SettingsDaemon.Rfkill ---- */

static const _ExtendedGDBusPropertyInfo _gf_sd_rfkill_gen_property_info_airplane_mode =
{
  {
    -1,
    (gchar *) "AirplaneMode",
    (gchar *) "b",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE,
    NULL
  },
  "airplane-mode",
  FALSE,
  TRUE
};

static const _ExtendedGDBusPropertyInfo _gf_sd_rfkill_gen_property_info_hardware_airplane_mode =
{
  {
    -1,
    (gchar *) "HardwareAirplaneMode",
    (gchar *) "b",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "hardware-airplane-mode",
  FALSE,
  TRUE
};

static const _ExtendedGDBusPropertyInfo _gf_sd_rfkill_gen_property_info_has_airplane_mode =
{
  {
    -1,
    (gchar *) "HasAirplaneMode",
    (gchar *) "b",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "has-airplane-mode",
  FALSE,
  TRUE
};

static const _ExtendedGDBusPropertyInfo _gf_sd_rfkill_gen_property_info_should_show_airplane_mode =
{
  {
    -1,
    (gchar *) "ShouldShowAirplaneMode",
    (gchar *) "b",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "should-show-airplane-mode",
  FALSE,
  TRUE
};

static const _ExtendedGDBusPropertyInfo _gf_sd_rfkill_gen_property_info_bluetooth_airplane_mode =
{
  {
    -1,
    (gchar *) "BluetoothAirplaneMode",
    (gchar *) "b",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE | G_DBUS_PROPERTY_INFO_FLAGS_WRITABLE,
    NULL
  },
  "bluetooth-airplane-mode",
  FALSE,
  TRUE
};

static const _ExtendedGDBusPropertyInfo _gf_sd_rfkill_gen_property_info_bluetooth_hardware_airplane_mode =
{
  {
    -1,
    (gchar *) "BluetoothHardwareAirplaneMode",
    (gchar *) "b",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "bluetooth-hardware-airplane-mode",
  FALSE,
  TRUE
};

static const _ExtendedGDBusPropertyInfo _gf_sd_rfkill_gen_property_info_bluetooth_has_airplane_mode =
{
  {
    -1,
    (gchar *) "BluetoothHasAirplaneMode",
    (gchar *) "b",
    G_DBUS_PROPERTY_INFO_FLAGS_READABLE,
    NULL
  },
  "bluetooth-has-airplane-mode",
  FALSE,
  TRUE
};

static const GDBusPropertyInfo * const _gf_sd_rfkill_gen_property_info_pointers[] =
{
  &_gf_sd_rfkill_gen_property_info_airplane_mode.parent_struct,
  &_gf_sd_rfkill_gen_property_info_hardware_airplane_mode.parent_struct,
  &_gf_sd_rfkill_gen_property_info_has_airplane_mode.parent_struct,
  &_gf_sd_rfkill_gen_property_info_should_show_airplane_mode.parent_struct,
  &_gf_sd_rfkill_gen_property_info_bluetooth_airplane_mode.parent_struct,
  &_gf_sd_rfkill_gen_property_info_bluetooth_hardware_airplane_mode.parent_struct,
  &_gf_sd_rfkill_gen_property_info_bluetooth_has_airplane_mode.parent_struct,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _gf_sd_rfkill_gen_interface_info =
{
  {
    -1,
    (gchar *) "org.gnome.SettingsDaemon.Rfkill",
    NULL,
    NULL,
    (GDBusPropertyInfo **) &_gf_sd_rfkill_gen_property_info_pointers,
    NULL
  },
  "sd-rfkill-gen",
};


/**
 * gf_sd_rfkill_gen_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-org-gnome-SettingsDaemon-Rfkill.top_of_page">org.gnome.SettingsDaemon.Rfkill</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
gf_sd_rfkill_gen_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_gf_sd_rfkill_gen_interface_info.parent_struct;
}

/**
 * gf_sd_rfkill_gen_override_properties:
 * @klass: The class structure for a #GObject derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #GfSdRfkillGen interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
gf_sd_rfkill_gen_override_properties (GObjectClass *klass, guint property_id_begin)
{
  g_object_class_override_property (klass, property_id_begin++, "airplane-mode");
  g_object_class_override_property (klass, property_id_begin++, "hardware-airplane-mode");
  g_object_class_override_property (klass, property_id_begin++, "has-airplane-mode");
  g_object_class_override_property (klass, property_id_begin++, "should-show-airplane-mode");
  g_object_class_override_property (klass, property_id_begin++, "bluetooth-airplane-mode");
  g_object_class_override_property (klass, property_id_begin++, "bluetooth-hardware-airplane-mode");
  g_object_class_override_property (klass, property_id_begin++, "bluetooth-has-airplane-mode");
  return property_id_begin - 1;
}



/**
 * GfSdRfkillGen:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-gnome-SettingsDaemon-Rfkill.top_of_page">org.gnome.SettingsDaemon.Rfkill</link>.
 */

/**
 * GfSdRfkillGenIface:
 * @parent_iface: The parent interface.
 * @get_airplane_mode: Getter for the #GfSdRfkillGen:airplane-mode property.
 * @get_bluetooth_airplane_mode: Getter for the #GfSdRfkillGen:bluetooth-airplane-mode property.
 * @get_bluetooth_hardware_airplane_mode: Getter for the #GfSdRfkillGen:bluetooth-hardware-airplane-mode property.
 * @get_bluetooth_has_airplane_mode: Getter for the #GfSdRfkillGen:bluetooth-has-airplane-mode property.
 * @get_hardware_airplane_mode: Getter for the #GfSdRfkillGen:hardware-airplane-mode property.
 * @get_has_airplane_mode: Getter for the #GfSdRfkillGen:has-airplane-mode property.
 * @get_should_show_airplane_mode: Getter for the #GfSdRfkillGen:should-show-airplane-mode property.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-gnome-SettingsDaemon-Rfkill.top_of_page">org.gnome.SettingsDaemon.Rfkill</link>.
 */

typedef GfSdRfkillGenIface GfSdRfkillGenInterface;
G_DEFINE_INTERFACE (GfSdRfkillGen, gf_sd_rfkill_gen, G_TYPE_OBJECT)

static void
gf_sd_rfkill_gen_default_init (GfSdRfkillGenIface *iface)
{
  /* GObject properties for D-Bus properties: */
  /**
   * GfSdRfkillGen:airplane-mode:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-gnome-SettingsDaemon-Rfkill.AirplaneMode">"AirplaneMode"</link>.
   *
   * Since the D-Bus property for this #GObject property is both readable and writable, it is meaningful to both read from it and write to it on both the service- and client-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_boolean ("airplane-mode", "AirplaneMode", "AirplaneMode", FALSE, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * GfSdRfkillGen:hardware-airplane-mode:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-gnome-SettingsDaemon-Rfkill.HardwareAirplaneMode">"HardwareAirplaneMode"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_boolean ("hardware-airplane-mode", "HardwareAirplaneMode", "HardwareAirplaneMode", FALSE, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * GfSdRfkillGen:has-airplane-mode:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-gnome-SettingsDaemon-Rfkill.HasAirplaneMode">"HasAirplaneMode"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_boolean ("has-airplane-mode", "HasAirplaneMode", "HasAirplaneMode", FALSE, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * GfSdRfkillGen:should-show-airplane-mode:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-gnome-SettingsDaemon-Rfkill.ShouldShowAirplaneMode">"ShouldShowAirplaneMode"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_boolean ("should-show-airplane-mode", "ShouldShowAirplaneMode", "ShouldShowAirplaneMode", FALSE, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * GfSdRfkillGen:bluetooth-airplane-mode:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-gnome-SettingsDaemon-Rfkill.BluetoothAirplaneMode">"BluetoothAirplaneMode"</link>.
   *
   * Since the D-Bus property for this #GObject property is both readable and writable, it is meaningful to both read from it and write to it on both the service- and client-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_boolean ("bluetooth-airplane-mode", "BluetoothAirplaneMode", "BluetoothAirplaneMode", FALSE, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * GfSdRfkillGen:bluetooth-hardware-airplane-mode:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-gnome-SettingsDaemon-Rfkill.BluetoothHardwareAirplaneMode">"BluetoothHardwareAirplaneMode"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_boolean ("bluetooth-hardware-airplane-mode", "BluetoothHardwareAirplaneMode", "BluetoothHardwareAirplaneMode", FALSE, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
  /**
   * GfSdRfkillGen:bluetooth-has-airplane-mode:
   *
   * Represents the D-Bus property <link linkend="gdbus-property-org-gnome-SettingsDaemon-Rfkill.BluetoothHasAirplaneMode">"BluetoothHasAirplaneMode"</link>.
   *
   * Since the D-Bus property for this #GObject property is readable but not writable, it is meaningful to read from it on both the client- and service-side. It is only meaningful, however, to write to it on the service-side.
   */
  g_object_interface_install_property (iface,
    g_param_spec_boolean ("bluetooth-has-airplane-mode", "BluetoothHasAirplaneMode", "BluetoothHasAirplaneMode", FALSE, G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS));
}

/**
 * gf_sd_rfkill_gen_get_airplane_mode: (skip)
 * @object: A #GfSdRfkillGen.
 *
 * Gets the value of the <link linkend="gdbus-property-org-gnome-SettingsDaemon-Rfkill.AirplaneMode">"AirplaneMode"</link> D-Bus property.
 *
 * Since this D-Bus property is both readable and writable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: The property value.
 */
gboolean 
gf_sd_rfkill_gen_get_airplane_mode (GfSdRfkillGen *object)
{
  return GF_SD_RFKILL_GEN_GET_IFACE (object)->get_airplane_mode (object);
}

/**
 * gf_sd_rfkill_gen_set_airplane_mode: (skip)
 * @object: A #GfSdRfkillGen.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-gnome-SettingsDaemon-Rfkill.AirplaneMode">"AirplaneMode"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is both readable and writable, it is meaningful to use this function on both the client- and service-side.
 */
void
gf_sd_rfkill_gen_set_airplane_mode (GfSdRfkillGen *object, gboolean value)
{
  g_object_set (G_OBJECT (object), "airplane-mode", value, NULL);
}

/**
 * gf_sd_rfkill_gen_get_hardware_airplane_mode: (skip)
 * @object: A #GfSdRfkillGen.
 *
 * Gets the value of the <link linkend="gdbus-property-org-gnome-SettingsDaemon-Rfkill.HardwareAirplaneMode">"HardwareAirplaneMode"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: The property value.
 */
gboolean 
gf_sd_rfkill_gen_get_hardware_airplane_mode (GfSdRfkillGen *object)
{
  return GF_SD_RFKILL_GEN_GET_IFACE (object)->get_hardware_airplane_mode (object);
}

/**
 * gf_sd_rfkill_gen_set_hardware_airplane_mode: (skip)
 * @object: A #GfSdRfkillGen.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-gnome-SettingsDaemon-Rfkill.HardwareAirplaneMode">"HardwareAirplaneMode"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
gf_sd_rfkill_gen_set_hardware_airplane_mode (GfSdRfkillGen *object, gboolean value)
{
  g_object_set (G_OBJECT (object), "hardware-airplane-mode", value, NULL);
}

/**
 * gf_sd_rfkill_gen_get_has_airplane_mode: (skip)
 * @object: A #GfSdRfkillGen.
 *
 * Gets the value of the <link linkend="gdbus-property-org-gnome-SettingsDaemon-Rfkill.HasAirplaneMode">"HasAirplaneMode"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: The property value.
 */
gboolean 
gf_sd_rfkill_gen_get_has_airplane_mode (GfSdRfkillGen *object)
{
  return GF_SD_RFKILL_GEN_GET_IFACE (object)->get_has_airplane_mode (object);
}

/**
 * gf_sd_rfkill_gen_set_has_airplane_mode: (skip)
 * @object: A #GfSdRfkillGen.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-gnome-SettingsDaemon-Rfkill.HasAirplaneMode">"HasAirplaneMode"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
gf_sd_rfkill_gen_set_has_airplane_mode (GfSdRfkillGen *object, gboolean value)
{
  g_object_set (G_OBJECT (object), "has-airplane-mode", value, NULL);
}

/**
 * gf_sd_rfkill_gen_get_should_show_airplane_mode: (skip)
 * @object: A #GfSdRfkillGen.
 *
 * Gets the value of the <link linkend="gdbus-property-org-gnome-SettingsDaemon-Rfkill.ShouldShowAirplaneMode">"ShouldShowAirplaneMode"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: The property value.
 */
gboolean 
gf_sd_rfkill_gen_get_should_show_airplane_mode (GfSdRfkillGen *object)
{
  return GF_SD_RFKILL_GEN_GET_IFACE (object)->get_should_show_airplane_mode (object);
}

/**
 * gf_sd_rfkill_gen_set_should_show_airplane_mode: (skip)
 * @object: A #GfSdRfkillGen.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-gnome-SettingsDaemon-Rfkill.ShouldShowAirplaneMode">"ShouldShowAirplaneMode"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
gf_sd_rfkill_gen_set_should_show_airplane_mode (GfSdRfkillGen *object, gboolean value)
{
  g_object_set (G_OBJECT (object), "should-show-airplane-mode", value, NULL);
}

/**
 * gf_sd_rfkill_gen_get_bluetooth_airplane_mode: (skip)
 * @object: A #GfSdRfkillGen.
 *
 * Gets the value of the <link linkend="gdbus-property-org-gnome-SettingsDaemon-Rfkill.BluetoothAirplaneMode">"BluetoothAirplaneMode"</link> D-Bus property.
 *
 * Since this D-Bus property is both readable and writable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: The property value.
 */
gboolean 
gf_sd_rfkill_gen_get_bluetooth_airplane_mode (GfSdRfkillGen *object)
{
  return GF_SD_RFKILL_GEN_GET_IFACE (object)->get_bluetooth_airplane_mode (object);
}

/**
 * gf_sd_rfkill_gen_set_bluetooth_airplane_mode: (skip)
 * @object: A #GfSdRfkillGen.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-gnome-SettingsDaemon-Rfkill.BluetoothAirplaneMode">"BluetoothAirplaneMode"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is both readable and writable, it is meaningful to use this function on both the client- and service-side.
 */
void
gf_sd_rfkill_gen_set_bluetooth_airplane_mode (GfSdRfkillGen *object, gboolean value)
{
  g_object_set (G_OBJECT (object), "bluetooth-airplane-mode", value, NULL);
}

/**
 * gf_sd_rfkill_gen_get_bluetooth_hardware_airplane_mode: (skip)
 * @object: A #GfSdRfkillGen.
 *
 * Gets the value of the <link linkend="gdbus-property-org-gnome-SettingsDaemon-Rfkill.BluetoothHardwareAirplaneMode">"BluetoothHardwareAirplaneMode"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: The property value.
 */
gboolean 
gf_sd_rfkill_gen_get_bluetooth_hardware_airplane_mode (GfSdRfkillGen *object)
{
  return GF_SD_RFKILL_GEN_GET_IFACE (object)->get_bluetooth_hardware_airplane_mode (object);
}

/**
 * gf_sd_rfkill_gen_set_bluetooth_hardware_airplane_mode: (skip)
 * @object: A #GfSdRfkillGen.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-gnome-SettingsDaemon-Rfkill.BluetoothHardwareAirplaneMode">"BluetoothHardwareAirplaneMode"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
gf_sd_rfkill_gen_set_bluetooth_hardware_airplane_mode (GfSdRfkillGen *object, gboolean value)
{
  g_object_set (G_OBJECT (object), "bluetooth-hardware-airplane-mode", value, NULL);
}

/**
 * gf_sd_rfkill_gen_get_bluetooth_has_airplane_mode: (skip)
 * @object: A #GfSdRfkillGen.
 *
 * Gets the value of the <link linkend="gdbus-property-org-gnome-SettingsDaemon-Rfkill.BluetoothHasAirplaneMode">"BluetoothHasAirplaneMode"</link> D-Bus property.
 *
 * Since this D-Bus property is readable, it is meaningful to use this function on both the client- and service-side.
 *
 * Returns: The property value.
 */
gboolean 
gf_sd_rfkill_gen_get_bluetooth_has_airplane_mode (GfSdRfkillGen *object)
{
  return GF_SD_RFKILL_GEN_GET_IFACE (object)->get_bluetooth_has_airplane_mode (object);
}

/**
 * gf_sd_rfkill_gen_set_bluetooth_has_airplane_mode: (skip)
 * @object: A #GfSdRfkillGen.
 * @value: The value to set.
 *
 * Sets the <link linkend="gdbus-property-org-gnome-SettingsDaemon-Rfkill.BluetoothHasAirplaneMode">"BluetoothHasAirplaneMode"</link> D-Bus property to @value.
 *
 * Since this D-Bus property is not writable, it is only meaningful to use this function on the service-side.
 */
void
gf_sd_rfkill_gen_set_bluetooth_has_airplane_mode (GfSdRfkillGen *object, gboolean value)
{
  g_object_set (G_OBJECT (object), "bluetooth-has-airplane-mode", value, NULL);
}

/* ------------------------------------------------------------------------ */

/**
 * GfSdRfkillGenProxy:
 *
 * The #GfSdRfkillGenProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * GfSdRfkillGenProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #GfSdRfkillGenProxy.
 */

struct _GfSdRfkillGenProxyPrivate
{
  GData *qdata;
};

static void gf_sd_rfkill_gen_proxy_iface_init (GfSdRfkillGenIface *iface);

#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (GfSdRfkillGenProxy, gf_sd_rfkill_gen_proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (GfSdRfkillGenProxy)
                         G_IMPLEMENT_INTERFACE (GF_TYPE_SD_RFKILL_GEN, gf_sd_rfkill_gen_proxy_iface_init))

#else
G_DEFINE_TYPE_WITH_CODE (GfSdRfkillGenProxy, gf_sd_rfkill_gen_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (GF_TYPE_SD_RFKILL_GEN, gf_sd_rfkill_gen_proxy_iface_init))

#endif
static void
gf_sd_rfkill_gen_proxy_finalize (GObject *object)
{
  GfSdRfkillGenProxy *proxy = GF_SD_RFKILL_GEN_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (gf_sd_rfkill_gen_proxy_parent_class)->finalize (object);
}

static void
gf_sd_rfkill_gen_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 7);
  info = (const _ExtendedGDBusPropertyInfo *) _gf_sd_rfkill_gen_property_info_pointers[prop_id - 1];
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (object), info->parent_struct.name);
  if (info->use_gvariant)
    {
      g_value_set_variant (value, variant);
    }
  else
    {
      if (variant != NULL)
        g_dbus_gvariant_to_gvalue (variant, value);
    }
  if (variant != NULL)
    g_variant_unref (variant);
}

static void
gf_sd_rfkill_gen_proxy_set_property_cb (GDBusProxy *proxy,
  GAsyncResult *res,
  gpointer      user_data)
{
  const _ExtendedGDBusPropertyInfo *info = user_data;
  GError *error;
  GVariant *_ret;
  error = NULL;
  _ret = g_dbus_proxy_call_finish (proxy, res, &error);
  if (!_ret)
    {
      g_warning ("Error setting property '%s' on interface org.gnome.SettingsDaemon.Rfkill: %s (%s, %d)",
                 info->parent_struct.name, 
                 error->message, g_quark_to_string (error->domain), error->code);
      g_error_free (error);
    }
  else
    {
      g_variant_unref (_ret);
    }
}

static void
gf_sd_rfkill_gen_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  const _ExtendedGDBusPropertyInfo *info;
  GVariant *variant;
  g_assert (prop_id != 0 && prop_id - 1 < 7);
  info = (const _ExtendedGDBusPropertyInfo *) _gf_sd_rfkill_gen_property_info_pointers[prop_id - 1];
  variant = g_dbus_gvalue_to_gvariant (value, G_VARIANT_TYPE (info->parent_struct.signature));
  g_dbus_proxy_call (G_DBUS_PROXY (object),
    "org.freedesktop.DBus.Properties.Set",
    g_variant_new ("(ssv)", "org.gnome.SettingsDaemon.Rfkill", info->parent_struct.name, variant),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    NULL, (GAsyncReadyCallback) gf_sd_rfkill_gen_proxy_set_property_cb, (GDBusPropertyInfo *) &info->parent_struct);
  g_variant_unref (variant);
}

static void
gf_sd_rfkill_gen_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  gsize num_params;
  gsize n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_gf_sd_rfkill_gen_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], GF_TYPE_SD_RFKILL_GEN);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, GF_TYPE_SD_RFKILL_GEN);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
gf_sd_rfkill_gen_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  GfSdRfkillGenProxy *proxy = GF_SD_RFKILL_GEN_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_gf_sd_rfkill_gen_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_gf_sd_rfkill_gen_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static gboolean 
gf_sd_rfkill_gen_proxy_get_airplane_mode (GfSdRfkillGen *object)
{
  GfSdRfkillGenProxy *proxy = GF_SD_RFKILL_GEN_PROXY (object);
  GVariant *variant;
  gboolean value = 0;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "AirplaneMode");
  if (variant != NULL)
    {
      value = g_variant_get_boolean (variant);
      g_variant_unref (variant);
    }
  return value;
}

static gboolean 
gf_sd_rfkill_gen_proxy_get_hardware_airplane_mode (GfSdRfkillGen *object)
{
  GfSdRfkillGenProxy *proxy = GF_SD_RFKILL_GEN_PROXY (object);
  GVariant *variant;
  gboolean value = 0;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "HardwareAirplaneMode");
  if (variant != NULL)
    {
      value = g_variant_get_boolean (variant);
      g_variant_unref (variant);
    }
  return value;
}

static gboolean 
gf_sd_rfkill_gen_proxy_get_has_airplane_mode (GfSdRfkillGen *object)
{
  GfSdRfkillGenProxy *proxy = GF_SD_RFKILL_GEN_PROXY (object);
  GVariant *variant;
  gboolean value = 0;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "HasAirplaneMode");
  if (variant != NULL)
    {
      value = g_variant_get_boolean (variant);
      g_variant_unref (variant);
    }
  return value;
}

static gboolean 
gf_sd_rfkill_gen_proxy_get_should_show_airplane_mode (GfSdRfkillGen *object)
{
  GfSdRfkillGenProxy *proxy = GF_SD_RFKILL_GEN_PROXY (object);
  GVariant *variant;
  gboolean value = 0;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "ShouldShowAirplaneMode");
  if (variant != NULL)
    {
      value = g_variant_get_boolean (variant);
      g_variant_unref (variant);
    }
  return value;
}

static gboolean 
gf_sd_rfkill_gen_proxy_get_bluetooth_airplane_mode (GfSdRfkillGen *object)
{
  GfSdRfkillGenProxy *proxy = GF_SD_RFKILL_GEN_PROXY (object);
  GVariant *variant;
  gboolean value = 0;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "BluetoothAirplaneMode");
  if (variant != NULL)
    {
      value = g_variant_get_boolean (variant);
      g_variant_unref (variant);
    }
  return value;
}

static gboolean 
gf_sd_rfkill_gen_proxy_get_bluetooth_hardware_airplane_mode (GfSdRfkillGen *object)
{
  GfSdRfkillGenProxy *proxy = GF_SD_RFKILL_GEN_PROXY (object);
  GVariant *variant;
  gboolean value = 0;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "BluetoothHardwareAirplaneMode");
  if (variant != NULL)
    {
      value = g_variant_get_boolean (variant);
      g_variant_unref (variant);
    }
  return value;
}

static gboolean 
gf_sd_rfkill_gen_proxy_get_bluetooth_has_airplane_mode (GfSdRfkillGen *object)
{
  GfSdRfkillGenProxy *proxy = GF_SD_RFKILL_GEN_PROXY (object);
  GVariant *variant;
  gboolean value = 0;
  variant = g_dbus_proxy_get_cached_property (G_DBUS_PROXY (proxy), "BluetoothHasAirplaneMode");
  if (variant != NULL)
    {
      value = g_variant_get_boolean (variant);
      g_variant_unref (variant);
    }
  return value;
}

static void
gf_sd_rfkill_gen_proxy_init (GfSdRfkillGenProxy *proxy)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  proxy->priv = gf_sd_rfkill_gen_proxy_get_instance_private (proxy);
#else
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, GF_TYPE_SD_RFKILL_GEN_PROXY, GfSdRfkillGenProxyPrivate);
#endif

  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), gf_sd_rfkill_gen_interface_info ());
}

static void
gf_sd_rfkill_gen_proxy_class_init (GfSdRfkillGenProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = gf_sd_rfkill_gen_proxy_finalize;
  gobject_class->get_property = gf_sd_rfkill_gen_proxy_get_property;
  gobject_class->set_property = gf_sd_rfkill_gen_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = gf_sd_rfkill_gen_proxy_g_signal;
  proxy_class->g_properties_changed = gf_sd_rfkill_gen_proxy_g_properties_changed;

  gf_sd_rfkill_gen_override_properties (gobject_class, 1);

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (GfSdRfkillGenProxyPrivate));
#endif
}

static void
gf_sd_rfkill_gen_proxy_iface_init (GfSdRfkillGenIface *iface)
{
  iface->get_airplane_mode = gf_sd_rfkill_gen_proxy_get_airplane_mode;
  iface->get_hardware_airplane_mode = gf_sd_rfkill_gen_proxy_get_hardware_airplane_mode;
  iface->get_has_airplane_mode = gf_sd_rfkill_gen_proxy_get_has_airplane_mode;
  iface->get_should_show_airplane_mode = gf_sd_rfkill_gen_proxy_get_should_show_airplane_mode;
  iface->get_bluetooth_airplane_mode = gf_sd_rfkill_gen_proxy_get_bluetooth_airplane_mode;
  iface->get_bluetooth_hardware_airplane_mode = gf_sd_rfkill_gen_proxy_get_bluetooth_hardware_airplane_mode;
  iface->get_bluetooth_has_airplane_mode = gf_sd_rfkill_gen_proxy_get_bluetooth_has_airplane_mode;
}

/**
 * gf_sd_rfkill_gen_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (nullable): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-gnome-SettingsDaemon-Rfkill.top_of_page">org.gnome.SettingsDaemon.Rfkill</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call gf_sd_rfkill_gen_proxy_new_finish() to get the result of the operation.
 *
 * See gf_sd_rfkill_gen_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
gf_sd_rfkill_gen_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (GF_TYPE_SD_RFKILL_GEN_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.gnome.SettingsDaemon.Rfkill", NULL);
}

/**
 * gf_sd_rfkill_gen_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gf_sd_rfkill_gen_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with gf_sd_rfkill_gen_proxy_new().
 *
 * Returns: (transfer full) (type GfSdRfkillGenProxy): The constructed proxy object or %NULL if @error is set.
 */
GfSdRfkillGen *
gf_sd_rfkill_gen_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return GF_SD_RFKILL_GEN (ret);
  else
    return NULL;
}

/**
 * gf_sd_rfkill_gen_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (nullable): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-gnome-SettingsDaemon-Rfkill.top_of_page">org.gnome.SettingsDaemon.Rfkill</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See gf_sd_rfkill_gen_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type GfSdRfkillGenProxy): The constructed proxy object or %NULL if @error is set.
 */
GfSdRfkillGen *
gf_sd_rfkill_gen_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (GF_TYPE_SD_RFKILL_GEN_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.gnome.SettingsDaemon.Rfkill", NULL);
  if (ret != NULL)
    return GF_SD_RFKILL_GEN (ret);
  else
    return NULL;
}


/**
 * gf_sd_rfkill_gen_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like gf_sd_rfkill_gen_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the thread-default main loop of the thread you are calling this method from (see g_main_context_push_thread_default()).
 * You can then call gf_sd_rfkill_gen_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See gf_sd_rfkill_gen_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
gf_sd_rfkill_gen_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (GF_TYPE_SD_RFKILL_GEN_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.gnome.SettingsDaemon.Rfkill", NULL);
}

/**
 * gf_sd_rfkill_gen_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to gf_sd_rfkill_gen_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with gf_sd_rfkill_gen_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type GfSdRfkillGenProxy): The constructed proxy object or %NULL if @error is set.
 */
GfSdRfkillGen *
gf_sd_rfkill_gen_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return GF_SD_RFKILL_GEN (ret);
  else
    return NULL;
}

/**
 * gf_sd_rfkill_gen_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (nullable): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like gf_sd_rfkill_gen_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See gf_sd_rfkill_gen_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type GfSdRfkillGenProxy): The constructed proxy object or %NULL if @error is set.
 */
GfSdRfkillGen *
gf_sd_rfkill_gen_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (GF_TYPE_SD_RFKILL_GEN_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.gnome.SettingsDaemon.Rfkill", NULL);
  if (ret != NULL)
    return GF_SD_RFKILL_GEN (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * GfSdRfkillGenSkeleton:
 *
 * The #GfSdRfkillGenSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * GfSdRfkillGenSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #GfSdRfkillGenSkeleton.
 */

struct _GfSdRfkillGenSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_gf_sd_rfkill_gen_skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  GfSdRfkillGenSkeleton *skeleton = GF_SD_RFKILL_GEN_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  gsize num_params;
  guint num_extra;
  gsize n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], GF_TYPE_SD_RFKILL_GEN);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, GF_TYPE_SD_RFKILL_GEN);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_gf_sd_rfkill_gen_skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  GfSdRfkillGenSkeleton *skeleton = GF_SD_RFKILL_GEN_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_gf_sd_rfkill_gen_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_gf_sd_rfkill_gen_skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  GfSdRfkillGenSkeleton *skeleton = GF_SD_RFKILL_GEN_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_gf_sd_rfkill_gen_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _gf_sd_rfkill_gen_skeleton_vtable =
{
  _gf_sd_rfkill_gen_skeleton_handle_method_call,
  _gf_sd_rfkill_gen_skeleton_handle_get_property,
  _gf_sd_rfkill_gen_skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
gf_sd_rfkill_gen_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return gf_sd_rfkill_gen_interface_info ();
}

static GDBusInterfaceVTable *
gf_sd_rfkill_gen_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_gf_sd_rfkill_gen_skeleton_vtable;
}

static GVariant *
gf_sd_rfkill_gen_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  GfSdRfkillGenSkeleton *skeleton = GF_SD_RFKILL_GEN_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_gf_sd_rfkill_gen_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _gf_sd_rfkill_gen_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _gf_sd_rfkill_gen_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _gf_sd_rfkill_gen_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.gnome.SettingsDaemon.Rfkill", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static gboolean _gf_sd_rfkill_gen_emit_changed (gpointer user_data);

static void
gf_sd_rfkill_gen_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
  GfSdRfkillGenSkeleton *skeleton = GF_SD_RFKILL_GEN_SKELETON (_skeleton);
  gboolean emit_changed = FALSE;

  g_mutex_lock (&skeleton->priv->lock);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    {
      g_source_destroy (skeleton->priv->changed_properties_idle_source);
      skeleton->priv->changed_properties_idle_source = NULL;
      emit_changed = TRUE;
    }
  g_mutex_unlock (&skeleton->priv->lock);

  if (emit_changed)
    _gf_sd_rfkill_gen_emit_changed (skeleton);
}

static void gf_sd_rfkill_gen_skeleton_iface_init (GfSdRfkillGenIface *iface);
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (GfSdRfkillGenSkeleton, gf_sd_rfkill_gen_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (GfSdRfkillGenSkeleton)
                         G_IMPLEMENT_INTERFACE (GF_TYPE_SD_RFKILL_GEN, gf_sd_rfkill_gen_skeleton_iface_init))

#else
G_DEFINE_TYPE_WITH_CODE (GfSdRfkillGenSkeleton, gf_sd_rfkill_gen_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (GF_TYPE_SD_RFKILL_GEN, gf_sd_rfkill_gen_skeleton_iface_init))

#endif
static void
gf_sd_rfkill_gen_skeleton_finalize (GObject *object)
{
  GfSdRfkillGenSkeleton *skeleton = GF_SD_RFKILL_GEN_SKELETON (object);
  guint n;
  for (n = 0; n < 7; n++)
    g_value_unset (&skeleton->priv->properties[n]);
  g_free (skeleton->priv->properties);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (gf_sd_rfkill_gen_skeleton_parent_class)->finalize (object);
}

static void
gf_sd_rfkill_gen_skeleton_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
  GfSdRfkillGenSkeleton *skeleton = GF_SD_RFKILL_GEN_SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 7);
  g_mutex_lock (&skeleton->priv->lock);
  g_value_copy (&skeleton->priv->properties[prop_id - 1], value);
  g_mutex_unlock (&skeleton->priv->lock);
}

static gboolean
_gf_sd_rfkill_gen_emit_changed (gpointer user_data)
{
  GfSdRfkillGenSkeleton *skeleton = GF_SD_RFKILL_GEN_SKELETON (user_data);
  GList *l;
  GVariantBuilder builder;
  GVariantBuilder invalidated_builder;
  guint num_changes;

  g_mutex_lock (&skeleton->priv->lock);
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  g_variant_builder_init (&invalidated_builder, G_VARIANT_TYPE ("as"));
  for (l = skeleton->priv->changed_properties, num_changes = 0; l != NULL; l = l->next)
    {
      ChangedProperty *cp = l->data;
      GVariant *variant;
      const GValue *cur_value;

      cur_value = &skeleton->priv->properties[cp->prop_id - 1];
      if (!_g_value_equal (cur_value, &cp->orig_value))
        {
          variant = g_dbus_gvalue_to_gvariant (cur_value, G_VARIANT_TYPE (cp->info->parent_struct.signature));
          g_variant_builder_add (&builder, "{sv}", cp->info->parent_struct.name, variant);
          g_variant_unref (variant);
          num_changes++;
        }
    }
  if (num_changes > 0)
    {
      GList *connections, *ll;
      GVariant *signal_variant;
      signal_variant = g_variant_ref_sink (g_variant_new ("(sa{sv}as)", "org.gnome.SettingsDaemon.Rfkill",
                                           &builder, &invalidated_builder));
      connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));
      for (ll = connections; ll != NULL; ll = ll->next)
        {
          GDBusConnection *connection = ll->data;

          g_dbus_connection_emit_signal (connection,
                                         NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)),
                                         "org.freedesktop.DBus.Properties",
                                         "PropertiesChanged",
                                         signal_variant,
                                         NULL);
        }
      g_variant_unref (signal_variant);
      g_list_free_full (connections, g_object_unref);
    }
  else
    {
      g_variant_builder_clear (&builder);
      g_variant_builder_clear (&invalidated_builder);
    }
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  skeleton->priv->changed_properties = NULL;
  skeleton->priv->changed_properties_idle_source = NULL;
  g_mutex_unlock (&skeleton->priv->lock);
  return FALSE;
}

static void
_gf_sd_rfkill_gen_schedule_emit_changed (GfSdRfkillGenSkeleton *skeleton, const _ExtendedGDBusPropertyInfo *info, guint prop_id, const GValue *orig_value)
{
  ChangedProperty *cp;
  GList *l;
  cp = NULL;
  for (l = skeleton->priv->changed_properties; l != NULL; l = l->next)
    {
      ChangedProperty *i_cp = l->data;
      if (i_cp->info == info)
        {
          cp = i_cp;
          break;
        }
    }
  if (cp == NULL)
    {
      cp = g_new0 (ChangedProperty, 1);
      cp->prop_id = prop_id;
      cp->info = info;
      skeleton->priv->changed_properties = g_list_prepend (skeleton->priv->changed_properties, cp);
      g_value_init (&cp->orig_value, G_VALUE_TYPE (orig_value));
      g_value_copy (orig_value, &cp->orig_value);
    }
}

static void
gf_sd_rfkill_gen_skeleton_notify (GObject      *object,
  GParamSpec *pspec G_GNUC_UNUSED)
{
  GfSdRfkillGenSkeleton *skeleton = GF_SD_RFKILL_GEN_SKELETON (object);
  g_mutex_lock (&skeleton->priv->lock);
  if (skeleton->priv->changed_properties != NULL &&
      skeleton->priv->changed_properties_idle_source == NULL)
    {
      skeleton->priv->changed_properties_idle_source = g_idle_source_new ();
      g_source_set_priority (skeleton->priv->changed_properties_idle_source, G_PRIORITY_DEFAULT);
      g_source_set_callback (skeleton->priv->changed_properties_idle_source, _gf_sd_rfkill_gen_emit_changed, g_object_ref (skeleton), (GDestroyNotify) g_object_unref);
      g_source_set_name (skeleton->priv->changed_properties_idle_source, "[generated] _gf_sd_rfkill_gen_emit_changed");
      g_source_attach (skeleton->priv->changed_properties_idle_source, skeleton->priv->context);
      g_source_unref (skeleton->priv->changed_properties_idle_source);
    }
  g_mutex_unlock (&skeleton->priv->lock);
}

static void
gf_sd_rfkill_gen_skeleton_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
  const _ExtendedGDBusPropertyInfo *info;
  GfSdRfkillGenSkeleton *skeleton = GF_SD_RFKILL_GEN_SKELETON (object);
  g_assert (prop_id != 0 && prop_id - 1 < 7);
  info = (const _ExtendedGDBusPropertyInfo *) _gf_sd_rfkill_gen_property_info_pointers[prop_id - 1];
  g_mutex_lock (&skeleton->priv->lock);
  g_object_freeze_notify (object);
  if (!_g_value_equal (value, &skeleton->priv->properties[prop_id - 1]))
    {
      if (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)) != NULL &&
          info->emits_changed_signal)
        _gf_sd_rfkill_gen_schedule_emit_changed (skeleton, info, prop_id, &skeleton->priv->properties[prop_id - 1]);
      g_value_copy (value, &skeleton->priv->properties[prop_id - 1]);
      g_object_notify_by_pspec (object, pspec);
    }
  g_mutex_unlock (&skeleton->priv->lock);
  g_object_thaw_notify (object);
}

static void
gf_sd_rfkill_gen_skeleton_init (GfSdRfkillGenSkeleton *skeleton)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  skeleton->priv = gf_sd_rfkill_gen_skeleton_get_instance_private (skeleton);
#else
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, GF_TYPE_SD_RFKILL_GEN_SKELETON, GfSdRfkillGenSkeletonPrivate);
#endif

  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
  skeleton->priv->properties = g_new0 (GValue, 7);
  g_value_init (&skeleton->priv->properties[0], G_TYPE_BOOLEAN);
  g_value_init (&skeleton->priv->properties[1], G_TYPE_BOOLEAN);
  g_value_init (&skeleton->priv->properties[2], G_TYPE_BOOLEAN);
  g_value_init (&skeleton->priv->properties[3], G_TYPE_BOOLEAN);
  g_value_init (&skeleton->priv->properties[4], G_TYPE_BOOLEAN);
  g_value_init (&skeleton->priv->properties[5], G_TYPE_BOOLEAN);
  g_value_init (&skeleton->priv->properties[6], G_TYPE_BOOLEAN);
}

static gboolean 
gf_sd_rfkill_gen_skeleton_get_airplane_mode (GfSdRfkillGen *object)
{
  GfSdRfkillGenSkeleton *skeleton = GF_SD_RFKILL_GEN_SKELETON (object);
  gboolean value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_boolean (&(skeleton->priv->properties[0]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static gboolean 
gf_sd_rfkill_gen_skeleton_get_hardware_airplane_mode (GfSdRfkillGen *object)
{
  GfSdRfkillGenSkeleton *skeleton = GF_SD_RFKILL_GEN_SKELETON (object);
  gboolean value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_boolean (&(skeleton->priv->properties[1]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static gboolean 
gf_sd_rfkill_gen_skeleton_get_has_airplane_mode (GfSdRfkillGen *object)
{
  GfSdRfkillGenSkeleton *skeleton = GF_SD_RFKILL_GEN_SKELETON (object);
  gboolean value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_boolean (&(skeleton->priv->properties[2]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static gboolean 
gf_sd_rfkill_gen_skeleton_get_should_show_airplane_mode (GfSdRfkillGen *object)
{
  GfSdRfkillGenSkeleton *skeleton = GF_SD_RFKILL_GEN_SKELETON (object);
  gboolean value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_boolean (&(skeleton->priv->properties[3]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static gboolean 
gf_sd_rfkill_gen_skeleton_get_bluetooth_airplane_mode (GfSdRfkillGen *object)
{
  GfSdRfkillGenSkeleton *skeleton = GF_SD_RFKILL_GEN_SKELETON (object);
  gboolean value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_boolean (&(skeleton->priv->properties[4]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static gboolean 
gf_sd_rfkill_gen_skeleton_get_bluetooth_hardware_airplane_mode (GfSdRfkillGen *object)
{
  GfSdRfkillGenSkeleton *skeleton = GF_SD_RFKILL_GEN_SKELETON (object);
  gboolean value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_boolean (&(skeleton->priv->properties[5]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static gboolean 
gf_sd_rfkill_gen_skeleton_get_bluetooth_has_airplane_mode (GfSdRfkillGen *object)
{
  GfSdRfkillGenSkeleton *skeleton = GF_SD_RFKILL_GEN_SKELETON (object);
  gboolean value;
  g_mutex_lock (&skeleton->priv->lock);
  value = g_value_get_boolean (&(skeleton->priv->properties[6]));
  g_mutex_unlock (&skeleton->priv->lock);
  return value;
}

static void
gf_sd_rfkill_gen_skeleton_class_init (GfSdRfkillGenSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = gf_sd_rfkill_gen_skeleton_finalize;
  gobject_class->get_property = gf_sd_rfkill_gen_skeleton_get_property;
  gobject_class->set_property = gf_sd_rfkill_gen_skeleton_set_property;
  gobject_class->notify       = gf_sd_rfkill_gen_skeleton_notify;


  gf_sd_rfkill_gen_override_properties (gobject_class, 1);

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = gf_sd_rfkill_gen_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = gf_sd_rfkill_gen_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = gf_sd_rfkill_gen_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = gf_sd_rfkill_gen_skeleton_dbus_interface_get_vtable;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (GfSdRfkillGenSkeletonPrivate));
#endif
}

static void
gf_sd_rfkill_gen_skeleton_iface_init (GfSdRfkillGenIface *iface)
{
  iface->get_airplane_mode = gf_sd_rfkill_gen_skeleton_get_airplane_mode;
  iface->get_hardware_airplane_mode = gf_sd_rfkill_gen_skeleton_get_hardware_airplane_mode;
  iface->get_has_airplane_mode = gf_sd_rfkill_gen_skeleton_get_has_airplane_mode;
  iface->get_should_show_airplane_mode = gf_sd_rfkill_gen_skeleton_get_should_show_airplane_mode;
  iface->get_bluetooth_airplane_mode = gf_sd_rfkill_gen_skeleton_get_bluetooth_airplane_mode;
  iface->get_bluetooth_hardware_airplane_mode = gf_sd_rfkill_gen_skeleton_get_bluetooth_hardware_airplane_mode;
  iface->get_bluetooth_has_airplane_mode = gf_sd_rfkill_gen_skeleton_get_bluetooth_has_airplane_mode;
}

/**
 * gf_sd_rfkill_gen_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-gnome-SettingsDaemon-Rfkill.top_of_page">org.gnome.SettingsDaemon.Rfkill</link>.
 *
 * Returns: (transfer full) (type GfSdRfkillGenSkeleton): The skeleton object.
 */
GfSdRfkillGen *
gf_sd_rfkill_gen_skeleton_new (void)
{
  return GF_SD_RFKILL_GEN (g_object_new (GF_TYPE_SD_RFKILL_GEN_SKELETON, NULL));
}

