/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#ifndef __GF_SN_WATCHER_V0_GEN_H__
#define __GF_SN_WATCHER_V0_GEN_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.kde.StatusNotifierWatcher */

#define GF_TYPE_SN_WATCHER_V0_GEN (gf_sn_watcher_v0_gen_get_type ())
#define GF_SN_WATCHER_V0_GEN(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), GF_TYPE_SN_WATCHER_V0_GEN, GfSnWatcherV0Gen))
#define GF_IS_SN_WATCHER_V0_GEN(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), GF_TYPE_SN_WATCHER_V0_GEN))
#define GF_SN_WATCHER_V0_GEN_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), GF_TYPE_SN_WATCHER_V0_GEN, GfSnWatcherV0GenIface))

struct _GfSnWatcherV0Gen;
typedef struct _GfSnWatcherV0Gen GfSnWatcherV0Gen;
typedef struct _GfSnWatcherV0GenIface GfSnWatcherV0GenIface;

struct _GfSnWatcherV0GenIface
{
  GTypeInterface parent_iface;



  gboolean (*handle_register_host) (
    GfSnWatcherV0Gen *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_service);

  gboolean (*handle_register_item) (
    GfSnWatcherV0Gen *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_service);

  gboolean  (*get_is_host_registered) (GfSnWatcherV0Gen *object);

  gint  (*get_protocol_version) (GfSnWatcherV0Gen *object);

  const gchar *const * (*get_registered_items) (GfSnWatcherV0Gen *object);

  void (*host_registered) (
    GfSnWatcherV0Gen *object);

  void (*item_registered) (
    GfSnWatcherV0Gen *object,
    const gchar *arg_service);

  void (*item_unregistered) (
    GfSnWatcherV0Gen *object,
    const gchar *arg_service);

};

GType gf_sn_watcher_v0_gen_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *gf_sn_watcher_v0_gen_interface_info (void);
guint gf_sn_watcher_v0_gen_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void gf_sn_watcher_v0_gen_complete_register_item (
    GfSnWatcherV0Gen *object,
    GDBusMethodInvocation *invocation);

void gf_sn_watcher_v0_gen_complete_register_host (
    GfSnWatcherV0Gen *object,
    GDBusMethodInvocation *invocation);



/* D-Bus signal emissions functions: */
void gf_sn_watcher_v0_gen_emit_item_registered (
    GfSnWatcherV0Gen *object,
    const gchar *arg_service);

void gf_sn_watcher_v0_gen_emit_item_unregistered (
    GfSnWatcherV0Gen *object,
    const gchar *arg_service);

void gf_sn_watcher_v0_gen_emit_host_registered (
    GfSnWatcherV0Gen *object);



/* D-Bus method calls: */
void gf_sn_watcher_v0_gen_call_register_item (
    GfSnWatcherV0Gen *proxy,
    const gchar *arg_service,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean gf_sn_watcher_v0_gen_call_register_item_finish (
    GfSnWatcherV0Gen *proxy,
    GAsyncResult *res,
    GError **error);

gboolean gf_sn_watcher_v0_gen_call_register_item_sync (
    GfSnWatcherV0Gen *proxy,
    const gchar *arg_service,
    GCancellable *cancellable,
    GError **error);

void gf_sn_watcher_v0_gen_call_register_host (
    GfSnWatcherV0Gen *proxy,
    const gchar *arg_service,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean gf_sn_watcher_v0_gen_call_register_host_finish (
    GfSnWatcherV0Gen *proxy,
    GAsyncResult *res,
    GError **error);

gboolean gf_sn_watcher_v0_gen_call_register_host_sync (
    GfSnWatcherV0Gen *proxy,
    const gchar *arg_service,
    GCancellable *cancellable,
    GError **error);



/* D-Bus property accessors: */
const gchar *const *gf_sn_watcher_v0_gen_get_registered_items (GfSnWatcherV0Gen *object);
gchar **gf_sn_watcher_v0_gen_dup_registered_items (GfSnWatcherV0Gen *object);
void gf_sn_watcher_v0_gen_set_registered_items (GfSnWatcherV0Gen *object, const gchar *const *value);

gboolean gf_sn_watcher_v0_gen_get_is_host_registered (GfSnWatcherV0Gen *object);
void gf_sn_watcher_v0_gen_set_is_host_registered (GfSnWatcherV0Gen *object, gboolean value);

gint gf_sn_watcher_v0_gen_get_protocol_version (GfSnWatcherV0Gen *object);
void gf_sn_watcher_v0_gen_set_protocol_version (GfSnWatcherV0Gen *object, gint value);


/* ---- */

#define GF_TYPE_SN_WATCHER_V0_GEN_PROXY (gf_sn_watcher_v0_gen_proxy_get_type ())
#define GF_SN_WATCHER_V0_GEN_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), GF_TYPE_SN_WATCHER_V0_GEN_PROXY, GfSnWatcherV0GenProxy))
#define GF_SN_WATCHER_V0_GEN_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), GF_TYPE_SN_WATCHER_V0_GEN_PROXY, GfSnWatcherV0GenProxyClass))
#define GF_SN_WATCHER_V0_GEN_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), GF_TYPE_SN_WATCHER_V0_GEN_PROXY, GfSnWatcherV0GenProxyClass))
#define GF_IS_SN_WATCHER_V0_GEN_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), GF_TYPE_SN_WATCHER_V0_GEN_PROXY))
#define GF_IS_SN_WATCHER_V0_GEN_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), GF_TYPE_SN_WATCHER_V0_GEN_PROXY))

typedef struct _GfSnWatcherV0GenProxy GfSnWatcherV0GenProxy;
typedef struct _GfSnWatcherV0GenProxyClass GfSnWatcherV0GenProxyClass;
typedef struct _GfSnWatcherV0GenProxyPrivate GfSnWatcherV0GenProxyPrivate;

struct _GfSnWatcherV0GenProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  GfSnWatcherV0GenProxyPrivate *priv;
};

struct _GfSnWatcherV0GenProxyClass
{
  GDBusProxyClass parent_class;
};

GType gf_sn_watcher_v0_gen_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (GfSnWatcherV0GenProxy, g_object_unref)
#endif

void gf_sn_watcher_v0_gen_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
GfSnWatcherV0Gen *gf_sn_watcher_v0_gen_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
GfSnWatcherV0Gen *gf_sn_watcher_v0_gen_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void gf_sn_watcher_v0_gen_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
GfSnWatcherV0Gen *gf_sn_watcher_v0_gen_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
GfSnWatcherV0Gen *gf_sn_watcher_v0_gen_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define GF_TYPE_SN_WATCHER_V0_GEN_SKELETON (gf_sn_watcher_v0_gen_skeleton_get_type ())
#define GF_SN_WATCHER_V0_GEN_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), GF_TYPE_SN_WATCHER_V0_GEN_SKELETON, GfSnWatcherV0GenSkeleton))
#define GF_SN_WATCHER_V0_GEN_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), GF_TYPE_SN_WATCHER_V0_GEN_SKELETON, GfSnWatcherV0GenSkeletonClass))
#define GF_SN_WATCHER_V0_GEN_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), GF_TYPE_SN_WATCHER_V0_GEN_SKELETON, GfSnWatcherV0GenSkeletonClass))
#define GF_IS_SN_WATCHER_V0_GEN_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), GF_TYPE_SN_WATCHER_V0_GEN_SKELETON))
#define GF_IS_SN_WATCHER_V0_GEN_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), GF_TYPE_SN_WATCHER_V0_GEN_SKELETON))

typedef struct _GfSnWatcherV0GenSkeleton GfSnWatcherV0GenSkeleton;
typedef struct _GfSnWatcherV0GenSkeletonClass GfSnWatcherV0GenSkeletonClass;
typedef struct _GfSnWatcherV0GenSkeletonPrivate GfSnWatcherV0GenSkeletonPrivate;

struct _GfSnWatcherV0GenSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  GfSnWatcherV0GenSkeletonPrivate *priv;
};

struct _GfSnWatcherV0GenSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType gf_sn_watcher_v0_gen_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (GfSnWatcherV0GenSkeleton, g_object_unref)
#endif

GfSnWatcherV0Gen *gf_sn_watcher_v0_gen_skeleton_new (void);


G_END_DECLS

#endif /* __GF_SN_WATCHER_V0_GEN_H__ */
